Installed node-sass and compiled scass into css.
oaworks/oa-works pull request #132
Opened 2021-11-19 05:44 UTC by thinkbulecount2

https://github.com/oaworks/oa-works/issues/1

Installed node-sass and converted current CSS into SCSS, then ran the command to compile back into CSS. Did some checking with the compiled CSS just to see if anything broke — none so far! Would love people's inputs.

2022-02-24 02:32 UTC, thinkbulecount2 commented
TODOs from the [issue](https://github.com/oaworks/oa-works/issues/1) as well as changes to the file structure as outlined here:

oa-works/
`--- src/ 
     |--- _data/ 
     |--- _includes/
     |--- about/ 
     |--- developers/ 
     |--- impact/ 
     |--- newsletter/ 
     |--- people/   
     |--- policies/  
     |--- products   
     `--- assets / 
          |--- css/
          |    |--- base/ 
          |    |    `--- _fonts.scss (..) _inverted.scss
          |    |--- layout / 
          |    |    `--- _sections.scss (..) _footer.scss
          |    |--- components/
          |    |    `--- _animations.scss (..) _timeline.scss
          |    |--- page/
          |    |    `--- _homepage.scss (..) _markdown.scss
          |    `--- main.scss
          |--- favicons
          |--- fonts
          |--- img 
          `--- js 

- [x]  Finish Gulp SCSS setup!
- [x]  Move all static asset directories and files to the structure shown above (JS, favicons, fonts, img)
- [x]  Fix up URL paths in templates (they’ll be probably a bit everywhere, might need to Regex that), ensure all of these static files still work, and test them visually
- [x]  Rename all .css files to be .scss partials prefixed with _ — i.e. homepage.css becomes homepage.scss
- [x]  Create main.scss in the new css/directory
- [x]  Basing yourself on the structure and order of the current main.html (found in oa-works/src/), import all individual scss in that main.scssfile using the https://github.com/import rule
- [ ]  Test that all CSS output still works. Ghost Inspector might come in handy with this — we can do this together on our next call
- [x]  Write documentation

2022-02-24 17:51 UTC, sssoz requested changes

2022-02-24 17:51 UTC, sssoz commented on .eleventy.js
> +  // });
No need to comment out — OK to commit the change separately and write a message for this

2022-02-24 17:51 UTC, sssoz commented on .eleventy.js
> +  eleventyConfig.addPassthroughCopy('./src/assets/favicons/');
Agreed that we should move everything to an `assets/` directory; could we do this with the `main.css` file as well? You will also need to update the path in `<head>`

2022-02-24 17:54 UTC, sssoz commented
@thinkbulecount2 Another comment: now that static assets are in the `assets/` directory, we need to make sure all images use that path too. This needs to be done on the following pages (and check others to make sure): 

- Homepage
- Team
- Partners

<img width="1661" alt="Screenshot 2022-02-24 at 17 54 03" src="https://user-images.githubusercontent.com/6668406/155580099-cb352c93-c56b-4398-aa0a-cacfcef7eba7.png">

<img width="513" alt="Screenshot 2022-02-24 at 17 53 31" src="https://user-images.githubusercontent.com/6668406/155580011-4e073a90-9991-4f98-9c88-e01d01466eb7.png">

<img width="451" alt="Screenshot 2022-02-24 at 17 54 17" src="https://user-images.githubusercontent.com/6668406/155580121-8120610f-c669-40e4-866c-6f635c07fbf1.png">

<img width="555" alt="Screenshot 2022-02-24 at 17 54 27" src="https://user-images.githubusercontent.com/6668406/155580143-9f530979-fad0-461b-b330-3e1d6d0daf65.png">

2022-02-25 22:27 UTC, sssoz commented
@thinkbulecount2 Once you’ve made the corrections and are ready to have this PR reviewed, please assign me to this PR!

2022-02-25 22:31 UTC, thinkbulecount2 commented
Will do @sssoz!

2022-02-27 10:56 UTC, sssoz commented on .eleventy.js
> +  // });
@thinkbulecount2 please resolve review comments once they are done!

2022-02-27 20:43 UTC, thinkbulecount2 commented
> 

I think I've covered everything, @sssoz! Let me know if I've missed anything!

2022-03-01 17:22 UTC, sssoz commented
@thinkbulecount2 I’m still getting errors when running locally; the images aren’t loading: 

```
: https://oa.works/assets/img/stories/solar-panels.jpg
LazyImages - Input buffer has corrupt header: glib: XML parse error: Error domain 1 code 77 on line 554 column 34 of data: Premature end of data in tag html line 1
```

Could you check your setup locally as well and make sure the images load? I’ve deleted the `dist/` directory to ensure everything was re-compiled from scratch of course.

2022-03-01 17:25 UTC, sssoz commented
Just realised the site.base_url variable is wrong! Let me adjust my local settings first. sorry!

2022-03-01 17:25 UTC, merged

2022-03-01 17:27 UTC, sssoz commented
Just merged to develop to see if it works on dev.oa.works but it seems that stylesheets aren’t loading at all now: https://dev.oa.works/

2022-03-02 06:25 UTC, thinkbulecount2 commented
Just pushed an update, @sssoz, I think I've managed to fix all the snags.

2022-03-02 06:54 UTC, thinkbulecount2 commented
Don't know if I should create a new PR for the update — let me know which way works best, @sssoz!

2022-03-02 11:08 UTC, sssoz commented
@thinkbulecount2 when you push to the remote branch, it should show up here. Have you tried to?

2022-03-02 17:32 UTC, thinkbulecount2 commented
@sssoz, I did, but if you see here it's asking me to create a new pull request instead of updating this one >>
<img width="1227" alt="Screenshot 2022-03-02 at 12 31 59" src="https://user-images.githubusercontent.com/38994650/156416141-800f9e61-8cb8-414c-99ac-4ead5d156aaa.png">

2022-03-02 17:33 UTC, sssoz commented
Then in that case, go ahead and create one if that's what it's asking to do :)